### ISSUE TITLE
Tailwind 4 new theme variables approach

### ISSUE THREAD

**Issue by OlegSuncrown** [spartan-ng/spartan#640]
### Information

Greetings, with tailwind 4 there is no need to wrap theme variables into `hsl()` function. Tailwind also [recommends](https://tailwindcss.com/docs/theme#referencing-other-variables):

> When defining theme variables that reference other variables, use the inline option.

So you can do it like this
```css
@theme inline {
  /* --color-destructive: hsl(var(--destructive)); */
  --color-destructive: var(--destructive);
}

:root {
  /* --destructive: 0 84.2% 60.2%; */
  --destructive: hsl(0, 84%, 60%);
}
```

Also when to use css variables like this, it doesn't show color indicator in the code editor

<img width="467" alt="Image" src="https://github.com/user-attachments/assets/4ca06fa4-abb3-44f9-b9be-a620072fbdd1" />

Perhaps it would be better not to generate a separate file with @import `@spartan-ng/brain/hlm-tailwind-preset.css`; but to add the theme directly into the project's styles.css file? So in that case color indicators will work.

```css
/* ./styles.css */
@theme {
  /* --color-destructive: hsl(var(--destructive)); */
  --color-destructive: hsl(0, 84%, 60%);
  --color-primary: #16a34a;
  ...
}
```
<img width="495" alt="Image" src="https://github.com/user-attachments/assets/262137ff-0efb-47be-931a-19028e0fb362" />

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No
